name: Deploy to GCP Cloud Run

on:
  push:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: "us-central1"
  IMAGE: "gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-cloud-run:${{ github.sha }}"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker to use gcloud CLI as a credential helper
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: docker build -t $IMAGE .

      - name: Push Docker image
        run: docker push $IMAGE

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve -var="project_id=${{ env.PROJECT_ID }}" -var="region=${{ env.REGION }}" -var="image_url=${{ env.IMAGE }}"

      - name: Output Cloud Run URL
        working-directory: ./terraform
        run: terraform output cloud_run_url
